name: Build and Publish ILPT Module

on: 
  workflow_call:
    inputs:
      version:
        description: "Type of version bump for this release."
        required: false
        default: patch
        type: string
      changelog_path:
        description: "The path to your changelog file"
        type: string
        required: false
        default: "./changelog.md"
    secrets:
      NPMJS_ILPT_PUBLISH:
        required: true

jobs:
  build-and-publish:
    permissions:
      contents: write

    steps:
      - name: Checkout ðŸ’¼
        uses: actions/checkout@v4

      - name: Check @ilpt namespace ðŸ·ï¸
        run: |
          if [[ $(jq -r '.name' package.json) != @ilpt/* ]]; then
            echo "Package name must start with @ilpt/ namespace"
            exit 1
          fi

      - name: Check changelog ðŸ•µï¸
        run: |
          if [ ! -f "${{ inputs.changelog_path }}" ]; then
            echo "Changelog file not found!"
            exit 1
          fi
          if ! grep -q "### What's changed" ${{ inputs.changelog_path }}; then
            echo "Changelog file not correctly formatted! - The changelog file needs to start with ### What's changed"
            exit 1
          fi
          if ! grep -q "\-\-\-" ${{ inputs.changelog_path }}; then
            echo "Changelog file not correctly formatted! - The changelog file needs to contain a "---" delimiter"
            exit 1
          fi

      - name: Install Node.js ðŸ§©
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Check for critical vulnerabilities ðŸ”Ž
        run: npm audit --audit-level critical --omit=dev

      - name: Install dependencies ðŸ“¦
        run: npm ci

      - name: Run tests ðŸ§ª
        run: npm test

      - name: Build ðŸ—ï¸
        run: npm run build

      - name: Bump version ðŸ“ˆ
        id: version
        run: |
          git config --local user.email "github@infinitaslearning.com"
          git config --local user.name "GitHub Action"
          NEW_VERSION=$(npm version ${{ inputs.version }} --message $'Update version to %s\n\nAutomated version bump by GitHub Action.')
          git push --follow-tags --no-verify
          echo "new-version=${NEW_VERSION}" >> $GITHUB_OUTPUT
        if: inputs.version && inputs.version != 'none'

      - name: Set up NPM ðŸ”‘
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPMJS_ILPT_PUBLISH }}"

      - name: Publish ðŸš€
        run: npm publish --access public

      - name: Read the current changes ðŸ“–
        run: |
          # Grab the text between ### What's changed and ---
          sed -n '/### What'\''s changed/,/---/{//!p}' ${{inputs.changelog_path}} > ./current-changes.md

      - name: Echo the current changes ðŸ“–
        run: cat ./current-changes.md

      - name: Create release â›©ï¸
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set-version.outputs.new-version }}
          body_path: ./current-changes.md

      - name: Update changelog ðŸ“
        run: |
          VERSION=${{ steps.set-version.outputs.new-version }}
          DT=$(date +'%Y-%m-%d %H:%M')

          # Replace ### What's changed to the current release eg. #### Release v0.3.1
          sed "s/### What's changed/### Release $VERSION - $DT/" ${{inputs.changelog_path}} > tmp_changelog.md

          # Add the new What's changed section with a default release message
          echo -e "### What's changed\n\n- No changelog has been added to this release\n\n---\n" > ./tmp_top.md

          # Combine the two parts back into the original file
          cat tmp_top.md | cat - tmp_changelog.md  > temp && mv temp ${{inputs.changelog_path}}

          # Remove the temporary files
          rm ./tmp_top.md
          rm ./tmp_changelog.md

          # Commit the updated changelog
          git add ${{inputs.changelog_path}}
          git commit -m "Update changelog" -m "[skip ci]" --no-verify
          git push --no-verify