name: Build and Publish ILPT Module

on: 
  workflow_call:
    inputs:
      version:
        description: "Type of version bump for this release."
        required: false
        default: patch
        type: string
      changelog_path:
        description: "The path to your changelog file"
        type: string
        required: false
        default: "./changelog.md"
    secrets:
      NPMJS_ILPT_PUBLISH:
        required: true

jobs:
  build-and-publish:
    permissions:
      contents: write

    steps:
      - name: Checkout 💼
        uses: actions/checkout@v4

      - name: Check @ilpt namespace 🏷️
        run: |
          if [[ $(jq -r '.name' package.json) != @ilpt/* ]]; then
            echo "Package name must start with @ilpt/ namespace"
            exit 1
          fi

      - name: Check changelog 🕵️
        run: |
          if [ ! -f "${{ inputs.changelog_path }}" ]; then
            echo "Changelog file not found!"
            exit 1
          fi
          if ! grep -q "### What's changed" ${{ inputs.changelog_path }}; then
            echo "Changelog file not correctly formatted! - The changelog file needs to start with ### What's changed"
            exit 1
          fi
          if ! grep -q "\-\-\-" ${{ inputs.changelog_path }}; then
            echo "Changelog file not correctly formatted! - The changelog file needs to contain a "---" delimiter"
            exit 1
          fi

      - name: Install Node.js 🧩
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Check for critical vulnerabilities 🔎
        run: npm audit --audit-level critical --omit=dev

      - name: Install dependencies 📦
        run: npm ci

      - name: Run tests 🧪
        run: npm test

      - name: Build 🏗️
        run: npm run build

      - name: Bump version 📈
        id: version
        run: |
          git config --local user.email "github@infinitaslearning.com"
          git config --local user.name "GitHub Action"
          NEW_VERSION=$(npm version ${{ inputs.version }} --message $'Update version to %s\n\nAutomated version bump by GitHub Action.')
          git push --follow-tags --no-verify
          echo "new-version=${NEW_VERSION}" >> $GITHUB_OUTPUT
        if: inputs.version && inputs.version != 'none'

      - name: Read the current changes
        run: |
          # Grab the text between ### What's changed and ---
          sed -n '/### What'\''s changed/,/---/{//!p}' ${{inputs.changelog_path}} > ./current-changes.md

      - name: Update changelog 📝
        run: |
          VERSION=${{ steps.set-version.outputs.new-version }}
          DT=$(date +'%Y-%m-%d %H:%M')

          # Replace ### What's changed to the current release eg. #### Release v0.3.1
          sed -i "s/### What's changed/### Release $VERSION - $DT/" ${{inputs.changelog_path}}

      - name: Set up NPM 🔑
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPMJS_ILPT_PUBLISH }}"

      - name: Publish 🚀
        run: npm publish --access public

      - name: Create release ⛩️
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set-version.outputs.new-version }}
          body_path: ./current-changes.md

      - name: Prepare changelog for next release 📝
        run: |
          # Add the new What's changed section with a default release message
          sed -i "1i### What's changed\n\n- No changelog has been added to this release\n\n---\n" ${{inputs.changelog_path}}

          # Commit the updated changelog
          git add ${{inputs.changelog_path}}
          git commit -m "Update changelog" -m "[skip ci]" --no-verify
          git push --no-verify
